version: '3.8'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bsu_eng
      MYSQL_USER: bsu
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: bsu
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata:
